<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */
echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */
            echo __('Additional Information') ?></span></legend>
    <div class="field regulation required">
        <label for="regulation" class="label"><span><?php /* @escapeNotVerified */
                echo __('Besi Attribute') ?></span></label>
        <div class="control">
            <input type="text"  name="besi_attribute" id="besi_attribute" title="<?php /* @escapeNotVerified */
            echo __('Besi Attribute') ?>" class="input-text" data-validate="{required:true}">
        </div>
    </div>
    </fieldset>

